classes:
- system.linux.system.repo.docker
- system.kubernetes.pool.cluster
- system.salt.minion.cert.k8s_client
- system.salt.minion.cert.etcd_client
- cluster.virtual-mcp11-k8s-calico.infra
parameters:
  _param:
    kubernetes_calicoctl_image: calico/ctl:latest
    kubernetes_calico_image: calico/node:latest
    kubernetes_calico_cni_image: calico/cni:latest
    kubernetes_hyperkube_image: gcr.io/google_containers/hyperkube-amd64:v1.5.1
  docker:
    host:
      pkgs:
        - docker-engine=1.12.6-0~ubuntu-xenial
        - python-docker
  kubernetes:
    pool:
      network:
        etcd:
          ssl:
            enabled: true
        image: ${_param:kubernetes_calico_image}
        calicoctl:
          image: ${_param:kubernetes_calicoctl_image}
        cni:
          image: ${_param:kubernetes_calico_cni_image}
    common:
      hyperkube:
        image: ${_param:kubernetes_hyperkube_image}
  linux:
    network:
      resolv:
        dns:
          - 8.8.8.8
      interface:
        eth1:
          route:
            kubernetes_services:
              address: 10.254.0.0
              netmask: 255.255.0.0
              gateway: ${_param:single_address}
